SELECT COUNT(Nama) FROM ABSENSI WHERE KERJA_MASUK > '07.30.00';
SELECT Count(NAMA) FROM ABSENSI WHERE KERJA_MASUK >= '07.30.00';

--ijin
SELECT Count(KERJA_MASUK) AS IJIN FROM ABSENSI WHERE KERJA_MASUK = '00:00:00' ;
-- masuk + ijin
SELECT Count(KERJA_MASUK) AS MASUK FROM ABSENSI WHERE KERJA_MASUK <= '07:30:00';
--telat 
SELECT Count(KERJA_MASUK) AS TELAT FROM ABSENSI WHERE KERJA_MASUK >= '07:30:00';

SELECT * FROM ABSENSI WHERE KERJA_MASUK > '07.30.00';
use [1234_PRESENSI];